<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>qemu_hardware_interface</name>
  <version>0.0.1</version>
  <description>
    A custom ros2_control hardware interface plugin that bridges ROS 2 
    with a bare-metal ARM Cortex-M7 QEMU emulator over TCP.
  </description>
  
  <maintainer email="ayushshukla.personal@gmail.com">Ayush Shukla</maintainer>
  <license>MIT</license> <!-- Or Apache-2.0, standard for ROS 2 -->

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Core dependencies required to compile and run the plugin -->
  <depend>rclcpp</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>

  <!-- Defines this package as an ament-based ROS 2 package -->
  <export>
    <build_type>ament_cmake</build_type>
    <hardware_interface plugin="${prefix}/qemu_hardware_interface.xml"/>
  </export>
</package>